wandb_version: 1

run_name:
  desc: null
  value: CQL-DQN
env:
  desc: null
  value: CartPole-v0
episodes:
  desc: null
  value: 400
buffer_size:
  desc: null
  value: 100000
seed:
  desc: null
  value: 1
min_eps:
  desc: null
  value: 0.01
eps_frames:
  desc: null
  value: 10000.0
log_video:
  desc: null
  value: 0
save_every:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697706302.634755
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 3
      - 13
      - 16
      - 23
      4: 3.9.12
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
